#!/bin/bash

url=https://roms007.spxd007.workers.dev/0:/ssos1.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ssos1.tar.gz
echo "unzip done"
find ssos1.tar.gz -delete
