#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/ShapeShiftOS/platform_manifest.git
BRANCH=android_11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault

git config --global user.name "SP-XD"
git config --global user.email "somnatypaul007@gmail.com" 

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/SP-XD/vendor_asus_X01AD vendor/asus/X01AD 
git clone https://github.com/SP-XD/device_asus_X01AD.git -b shapeshift device/asus/X01AD
git clone https://github.com/SP-XD/kernel_asus_X01AD-1.git kernel/asus/X01AD
cd /tmp/rom
